dist: bionic
language: python

matrix:
  include:
    - python: "3.6"
      env: TOXENV=py36-pytest
    - python: "3.7"
      env: TOXENV=py37-pytest-coverage
    - python: "3.8"
      env: TOXENV=py38-pytest
    - python: "3.7"
      env: TOXENV=docs
    - python: "3.7"
      env: TOXENV=flake8

install:
  pip install tox

script:
  tox
